var a=10+2;
var b=10-2;
var c=10/2;
var d=10%2;
var e=10*2;
var f=10**2;
var g=2/5;
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(10==10);
console.log(10===10);
console.log(10==10.0);
console.log(10=='10');
console.log(10===10.0);
console.log(true=='1');
console.log(true==='1');
console.log(false==0);
console.log(false===0);
console.log(null==undefined);
console.log(null===undefined);
console.log(true=='0');
console.log(true=='');
console.log(false=="");
console.log(typeof(NaN));
console.log(10<NaN);
console.log(!true);
console.log(!NaN);
console.log(!undefined);
//bitwise operator 
var x=10;
var y=5;
console.log(x<<1);
console.log(x>>1);
console.log(x>>>1);
console.log(-10>>>1);